plugins {
    id 'com.android.library'
}

android {
    namespace 'black.hook'
    compileSdk 34

    defaultConfig {
        minSdk 21
        ndk {
            // Pastikan ini sesuai dengan file .a yang kamu punya
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation files('libs/reflection.jar')
}
