plugins {
    id 'com.android.library'
}

android {
    compileSdk 34
    namespace 'black.hook'
    defaultConfig {
        minSdk 21
        // Menentukan arsitektur HP yang didukung
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }
    
    dependencies {
    // Baris ini wajib ada untuk membaca file .jar di folder libs
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    // Opsional: Jika ingin lebih spesifik
    // implementation files('libs/reflection.jar')
    }

}
